name: Backend Build

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: sudo apt-get install build-essential procps curl file git

      - name: Install Homebrew script
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Add homebrew to path
        run: export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      
      - name: Install openCASCADE
        run: brew install opencascade

      - name: Apt update
        run: sudo apt-get update

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Create build directory
        working-directory: backend
        run: mkdir build

      - name: find opencascade
        run: sudo find /usr -name "OpenCASCADEConfig.cmake"

      - name: Cmake Build
        working-directory: backend/build
        run: cmake ..

      - name: Build Backend Project
        working-directory: backend/build
        run: make
