name: Tubender Build 

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build
        
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Install OpenCASCADE dependencies
      run: sudo apt-get install -y libopencascade-dev

    - name: Install OCCT dependencies
      run: sudo apt-get install -y libfreetype6-dev libgl2ps-dev libx11-dev libxt-dev libxmu-dev libxi-dev

    - name: Create build directory
      working-directory: backend
      run: mkdir build

    - name: Cmake Build
      working-directory: backend/build
      run: cmake ../..
    
    - name: Build Backend Project
      working-directory: backend/build
      run: make
